### ISSUE TITLE
Possibile to get added to NLP faculty list?

### ISSUE THREAD

**Issue by euangeleo** [clulab/nlp.arizona.edu#1]
I know I could fork the repo, add my info in `data/people.yml`, then make a pull request, but I noticed that this repo has no forks yet--so perhaps that is impolite in terms of the culture around this repo?

Anyway, I thought it would be best to ask first. :smile:

**Comment by MihaiSurdeanu** [comment]
Hi Eric,
No policy and no culture here :)
Just send us a PR in some way.

**Comment by kwalcock** [comment]
If this repo is related to https://nlp.arizona.edu/ or https://clulab.org/nlp.arizona.edu/ then I wonder if there is a better way to manage the links to people's images, many of which are broken.  Should local copies of the images be used or is it time to nag some people about updating their pictures?

**Comment by MihaiSurdeanu** [comment]
In process...

Thanks for checking!
